#

all:	semcreate semdel semacq semrel semcrd semcwr semall semstat semacreate semarel semaacq

semcreate:	semcreate.c
	gcc -Wall -o semcreate semcreate.c

semdel:	semdel.c
	gcc -Wall -o semdel semdel.c

semacq:	semacq.c
	gcc -Wall -o semacq semacq.c

semrel:	semrel.c
	gcc -Wall -o semrel semrel.c

semcrd:	semcrd.c
	gcc -Wall -o semcrd semcrd.c

semcwr:	semcwr.c
	gcc -Wall -o semcwr semcwr.c

semall:	semall.c
	gcc -Wall -o semall semall.c

semstat:semstat.c
	gcc -Wall -o semstat semstat.c

semacreate:semacreate.c
	gcc -Wall -o semacreate semacreate.c

semarel:semarel.c
	gcc -Wall -o semarel semarel.c

semaacq:semaacq.c
	gcc -Wall -o semaacq semaacq.c

clean:
	rm -rf semcreate semdel semacq semrel semcrd semcwr semall semstat semacreate semarel semaacq

